tcpjw3.oa/Controllers/TradingDataController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using tcpjw3.oa.Models;

namespace tcpjw3.oa.Controllers
{
    public class TradingDataController : Controller
    {
        private tcpjwEntities db = new tcpjwEntities();

        // GET: TradingData
        public ActionResult Index()
        {
            return View(db.BAT_TradingData.ToList());
        }

        // GET: TradingData/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BAT_TradingData bAT_TradingData = db.BAT_TradingData.Find(id);
            if (bAT_TradingData == null)
            {
                return HttpNotFound();
            }
            return View(bAT_TradingData);
        }

        // GET: TradingData/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: TradingData/Create
        // 为了防止“过多发布”攻击，请启用要绑定到的特定属性，有关 
        // 详细信息，请参阅 http://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,CountM,YesDayCountM,AvergeTime,OperTime,backup1,backup2,backup3")] BAT_TradingData bAT_TradingData)
        {
            if (ModelState.IsValid)
            {
                db.BAT_TradingData.Add(bAT_TradingData);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(bAT_TradingData);
        }

        // GET: TradingData/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BAT_TradingData bAT_TradingData = db.BAT_TradingData.Find(id);
            if (bAT_TradingData == null)
            {
                return HttpNotFound();
            }
            return View(bAT_TradingData);
        }

        // POST: TradingData/Edit/5
        // 为了防止“过多发布”攻击，请启用要绑定到的特定属性，有关 
        // 详细信息，请参阅 http://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,CountM,YesDayCountM,AvergeTime,OperTime,backup1,backup2,backup3")] BAT_TradingData bAT_TradingData)
        {
            if (ModelState.IsValid)
            {
                db.Entry(bAT_TradingData).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(bAT_TradingData);
        }

        // GET: TradingData/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BAT_TradingData bAT_TradingData = db.BAT_TradingData.Find(id);
            if (bAT_TradingData == null)
            {
                return HttpNotFound();
            }
            return View(bAT_TradingData);
        }

        // POST: TradingData/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            BAT_TradingData bAT_TradingData = db.BAT_TradingData.Find(id);
            db.BAT_TradingData.Remove(bAT_TradingData);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

tcpjw3.oa/Views/TradingData/Create.cshtml
@model tcpjw3.oa.Models.BAT_TradingData

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>
    @using (Html.BeginForm()) 
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>BAT_TradingData</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.ID, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ID, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ID, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.CountM, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.CountM, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CountM, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.YesDayCountM, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.YesDayCountM, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.YesDayCountM, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.AvergeTime, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.AvergeTime, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.AvergeTime, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.OperTime, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.OperTime, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.OperTime, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.backup1, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.backup1, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.backup1, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.backup2, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.backup2, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.backup2, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.backup3, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.backup3, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.backup3, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

tcpjw3.oa/Views/TradingData/Delete.cshtml
@model tcpjw3.oa.Models.BAT_TradingData

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>
    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>BAT_TradingData</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.CountM)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.CountM)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.YesDayCountM)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.YesDayCountM)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.AvergeTime)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.AvergeTime)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.OperTime)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.OperTime)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.backup1)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.backup1)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.backup2)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.backup2)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.backup3)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.backup3)
            </dd>
    
        </dl>
    
        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()
    
            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
</body>
</html>

tcpjw3.oa/Views/TradingData/Details.cshtml
@model tcpjw3.oa.Models.BAT_TradingData

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>
    <div>
        <h4>BAT_TradingData</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.CountM)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.CountM)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.YesDayCountM)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.YesDayCountM)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.AvergeTime)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.AvergeTime)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.OperTime)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.OperTime)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.backup1)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.backup1)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.backup2)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.backup2)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.backup3)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.backup3)
            </dd>
    
        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
</body>
</html>

tcpjw3.oa/Views/TradingData/Edit.cshtml
@model tcpjw3.oa.Models.BAT_TradingData

<style>
    .form-horizontal {
        margin-left:10px;
    }
    .col-md-10 {
    margin-top:20px;
    }
    .form-control {
    width:200px;
    height:25px;
    }
</style>

@using (Html.BeginForm("Edit", "TradingData",FormMethod.Post, "/TradingData/Index"))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>交易数据更新</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
        
            
            <div class="col-md-10">
                交易总额      @Html.EditorFor(model => model.CountM, new { htmlAttributes = new { @class = "form-control" } })
                   @Html.ValidationMessageFor(model => model.CountM, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
      
            <div class="col-md-10">
                上一交易日总额   @Html.EditorFor(model => model.YesDayCountM, new { htmlAttributes = new { @class = "form-control" ,@width="30px"} })
                @Html.ValidationMessageFor(model => model.YesDayCountM, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
         
            <div class="col-md-10">
                平均耗时   @Html.EditorFor(model => model.AvergeTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AvergeTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
           
            <div class="col-md-10">
                操作时间   @Html.EditorFor(model => model.OperTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OperTime, "", new { @class = "text-danger" })
            </div>
        </div>

        

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

tcpjw3.oa/Views/TradingData/Index.cshtml
@model IEnumerable<tcpjw3.oa.Models.BAT_TradingData>
@{
    ViewBag.Title = "交易数据管理";
}
<style>
    th {
        width:200px;
        
    }
    td {
        text-align:center;
    }
</style>
   
    <table class="table" style="margin-top:20px;">
        <tr>
            <th>
             

                交易总额
            </th>
            <th>
               上一交易日总额
            </th>
            <th>
              交易平均耗时
            </th>
            <th>
             操作时间
            </th>
            
            <th></th>
        </tr>
    
    @foreach (var item in Model) {
        <tr style="line-height: 3;">
            <td>
                @Html.DisplayFor(modelItem => item.CountM)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.YesDayCountM)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AvergeTime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.OperTime)
            </td>
          
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.ID }) 
             
            </td>
        </tr>
    }
    
    </table>